### ISSUE TITLE
[ problem ] Flakey example test

### ISSUE THREAD

**Issue by LukeLalor** [eidolon-ai/eidolon#890]
see https://github.com/eidolon-ai/eidolon/actions/runs/11728855994/attempts/1

it fails and then it passes.

**Comment by jrgleason** [comment]
Seems to be caused by 

```
ERROR - error calling tool convo_hello_world_question
Traceback (most recent call last):
  File "/home/jgleason/code/eidolon/eidolon-2/client/python/eidolon_ai_client/util/aiohttp.py", line 106, in check
    response.raise_for_status()
  File "/home/jgleason/.cache/pypoetry/virtualenvs/eidolon-examples-pdvKM6CJ-py3.11/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'http://localhost:8080/processes/67328fc4b6750c04473583fd/agent/hello_world/actions/question'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
```

**Comment by LukeLalor** [comment]
more notes after pairing,

Looks like the schema being given for the endpoint is wrong

We show a default for name (None) and that it is not required.

Unsure if this is happening on the swagger schema generation, or when parsing the swagger schema for tool. Real bug though somewhere.
