### ISSUE TITLE
[ problem ] GitHub Assistant (branch db/demo) permission denied error

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#946]
I got a `Failed to start AgentOS` and `Permission denied: '/data/eidolon/files'` error when running `sudo make docker-serve` on the GitHub Assistant (branch `db/demo`.

```
 => => naming to docker.io/library/github-assistant-agent-server:latest                                                                                                              0.0s
docker compose up 
[+] Running 1/0
 ✔ Container github-assistant-mongo-1  Running                                                                                                                                       0.0s 
Attaching to agent-server-1, mongo-1, webui-1
webui-1         |   ▲ Next.js 15.0.0-canary.123
webui-1         |   - Local:        http://6663fbb437b0:3000
webui-1         |   - Network:      http://172.20.0.4:3000
webui-1         | 
webui-1         |  ✓ Starting...
webui-1         |  ✓ Ready in 67ms
agent-server-1  | INFO:     Will watch for changes in these directories: ['/app', '/bound_resources']
agent-server-1  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
agent-server-1  | INFO:     Started reloader process [1] using WatchFiles
agent-server-1  | INFO:     Started server process [10]
agent-server-1  | INFO:     Waiting for application startup.
agent-server-1  | INFO - Skipping /bound_resources/README.md
agent-server-1  | INFO - Overriding builtin resource 'Reference.claude-3-5-sonnet-20240620'
agent-server-1  | INFO - Building machine 'github-assistant'
agent-server-1  | INFO - Starting agent 'repo_metadata_agent'
agent-server-1  | INFO - Starting agent 'chatbot'
agent-server-1  | INFO - Starting agent 'issues_agent'
agent-server-1  | INFO - Starting agent 'repo_code_search'
agent-server-1  | INFO - Starting agent 'git_agent'
agent-server-1  | INFO - Starting agent 'repo_doc_search'
agent-server-1  | INFO - Starting agent 'pull_request_agent'
agent-server-1  | INFO - Starting agent 'actions_agent'
agent-server-1  | INFO - Starting agent 'speech_agent'
agent-server-1  | ERROR - Failed to start AgentOS
agent-server-1  | Traceback (most recent call last):
agent-server-1  |   File "/usr/local/lib/python3.11/site-packages/eidolon_ai_sdk/bin/server.py", line 173, in start_os
agent-server-1  |     await machine.start(app)
agent-server-1  |   File "/usr/local/lib/python3.11/site-packages/eidolon_ai_sdk/system/agent_machine.py", line 157, in start
agent-server-1  |     await self.memory.start()
agent-server-1  |   File "/usr/local/lib/python3.11/site-packages/eidolon_ai_sdk/memory/agent_memory.py", line 24, in start
agent-server-1  |     await self.file_memory.start()
agent-server-1  |   File "/usr/local/lib/python3.11/site-packages/components/async_file_memory.py", line 160, in start
agent-server-1  |     self.root_dir.mkdir(parents=True)
agent-server-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
agent-server-1  |     os.mkdir(self, mode)
agent-server-1  | PermissionError: [Errno 13] Permission denied: '/data/eidolon/files'
```

**Comment by flynntsang** [comment]
More info. Got permission denied errors when trying to remove the github-assistant.

1. Shutdown server `sudo make docker-clean`
2. Clear out docker `sudo docker system prune -a`
3. Delete directory `rm -rf github-assistant/`

```rm: cannot remove 'github-assistant/dev-data/mongo/collection-2-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/journal': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/_mdb_catalog.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/WiredTigerHS.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/storage.bson': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/index-1-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/collection-4-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/WiredTiger.turtle': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/WiredTiger.lock': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/mongod.lock': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/sizeStorer.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/collection-0-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/index-6-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/WiredTiger': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/WiredTiger.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/index-5-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/index-3-11516072450734506491.wt': Permission denied
rm: cannot remove 'github-assistant/dev-data/mongo/diagnostic.data': Permission denied
rm: cannot remove 'github-assistant/dev-data/eidolon': Permission denied
```

**Comment by flynntsang** [comment]
This seems to be resolved.
